<?php
	require 'validation.php';
include('connection.php');


$secret = $_SESSION['secret'];
$user 	= $_SESSION['email'];

$_SESSION['compare'] = 	$_SESSION["confirmation"]==$_SESSION['googleCode'];


$query		= db_query("select * from  user where username='".$username."'");	
	$resuser = mysqli_num_rows($query);

        require_once 'googleLib/GoogleAuthenticator.php';
        $ga 		= new GoogleAuthenticator();
        $qrCodeUrl 	= $ga->getQRCodeGoogleUrl($user, $secret,'APCBA_Rizal');
  
?>

<!doctype html>
<html lang="en">
<head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Google Two Factor Authentication Login with PHP</title>
        <link rel="stylesheet" href="assets/css/bootstrap.min.css">
        <link rel="stylesheet" href="assets/css/layout.css">
        <link rel="stylesheet" href="assets/css/form-design.css">
		<link rel="stylesheet" href="assets/css/font-awesome.min.css">  
		
		
</head>
    <body class="wrapper">

        <!--Start area-->
        <section class="area">
            <div class="container">
           
                <div class="row justify-content-center">
                    <div class="col-lg-8">
                        <div class="form-area register-from">
                            <div class="form-content">
                                <center> <h2>Two-Factor Authentication (Demo) </h2></center>
                                <div class ="LOGO">

                            <Center><img src="img/school.png"  width="150" 
                              height="150"></Center>
                              
                                            </div>
                               <center > <p>Use this secret key <b>RBISOC3VTQPMQEGM</b> for your Google Authenticator and
                                Enter the verification code generated by it.</p></center>
                               
                               
                            </div>
                            <div class="form-input">
        <center>
            <h2>Enter Code</h2>
            <form name="reg" action="auth.php" method="POST">
                <div class="form-group">
                    <br><br><br>
                    <input type="text" name="code" id="code" autocomplete="off" value="" required>
                    <label>Enter Google Authenticator Code</label>
                </div>
                <div class="button">
                    <center>
                        <button name="login" type="submit" class="btn">Submit</button>
                    </center>
                </div>
            </form>
          
        </center>
    </div>
							
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </body>
</html>